### ISSUE TITLE
"Nothing" isn't interpreted correctly

### ISSUE THREAD

**Issue by torridgristle** [vantezzen/infinite-craft-solver#1]
When two items don't combine, Infinite Craft sends back `{"result":"Nothing","emoji":"","isNew":false}`. Infinite Craft Solver interprets that "Nothing" as a usable element.

This ends up being used as a step in things like Vapor where "Nothing" has to be combined with "Swamp" to get "Mosquito".

**Comment by vantezzen** [comment]
Thanks for reporting this - should be fixed now!
