### ISSUE TITLE
Impossible circular recipe sequences

### ISSUE THREAD

**Issue by LapisHusky** [vantezzen/infinite-craft-solver#2]
When searching for the recipe for Mosquito, one of the required elements is Itchy. However, the listed recipe for Itchy requires Mosquito. That's impossible to follow.

**Comment by Aiz0** [comment]
Theres also recipes which require the element itself such as these ones when searching mario
![image](https://github.com/vantezzen/infinite-craft-solver/assets/66974576/1f4f8762-1b9c-4397-bd42-b89267d8f85d)
You need to have pufferfish to get pufferfish and mario to get mario. That's not possible either.

**Comment by vantezzen** [comment]
I now reworked how the search algorithm works which is a bit slower but should bring more reliable results. It may take up to 48h until the cache clears the recipe for wrong paths but the updated Mosquito recipe path looks fine now
